Add remote dump collection mechanism
First roughly working PoC with ssh.

Signed-off-by: Louis Bouchard <louis.bouchard@ubuntu.com>

diff --git a/debian/kdump-config b/debian/kdump-config
--- a/debian/kdump-config
+++ b/debian/kdump-config
@@ -30,6 +30,11 @@ NAME=${NAME:="kdump-config"}
 
 . /lib/lsb/init-functions
 . /lib/init/vars.sh
+#
+# for debug only
+#
+. /usr/share/initramfs-tools/scripts/functions
+
 
 # Global Setup
 KDUMP_DEFAULTS=/etc/default/kdump-tools
@@ -357,6 +362,70 @@ function kdump_save_core()
 	fi
 }
 
+function kdump_save_core_to_ssh()
+{
+	KDUMP_STAMP=`date +"%Y%m%d%H%M"`
+	KDUMP_REMOTE_HOST=$SSH
+	KDUMP_STAMPDIR="$KDUMP_COREDIR/$KDUMP_STAMP"
+	KDUMP_CORETEMP="$KDUMP_STAMPDIR/dump-incomplete"
+	KDUMP_COREFILE="$KDUMP_STAMPDIR/dump.$KDUMP_STAMP"
+	KDUMP_TMPDMESG="/tmp/dmesg.$KDUMP_STAMP"
+	KDUMP_DMESGFILE="$KDUMP_STAMPDIR/dmesg.$KDUMP_STAMP"
+
+	ssh $KDUMP_REMOTE_HOST mkdir -p $KDUMP_STAMPDIR
+
+	log_action_msg "sending makedumpfile $MAKEDUMP_ARGS $vmcore_file to $KDUMP_REMOTE_HOST : $KDUMP_CORETEMP"
+	makedumpfile $MAKEDUMP_ARGS $vmcore_file | ssh $KDUMP_REMOTE_HOST dd of=$KDUMP_CORETEMP
+	if [ $? -ne 0 ] ; then
+		log_failure_msg "$NAME: makedumpfile failed, falling back to 'scp'"
+		logger -t $NAME "makedumpfile failed, falling back to 'scp'"
+		KDUMP_CORETEMP="$KDUMP_STAMPDIR/vmcore-incomplete"
+		KDUMP_COREFILE="$KDUMP_STAMPDIR/vmcore.$KDUMP_STAMP"
+		scp $vmcore_file $KDUMP_REMOTE_HOST:$KDUMP_CORETEMP
+		if [ $? -ne 0 ];then
+			log_failure_msg "$NAME: makedumpfile scp failed. The vmcore file will  not be available"
+			logger -t $NAME "makedumpfile scp failed. The vmcore file will  not be available"
+		else
+			success=1
+		fi
+	else
+		success=1
+	fi
+
+	# did we succeed?
+	if [ $success == 1 ]; then
+		ssh $KDUMP_REMOTE_HOST mv $KDUMP_CORETEMP $KDUMP_COREFILE
+		log_success_msg "$NAME: saved vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		logger -t $NAME "saved vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+	else
+		log_failure_msg "$NAME: failed to save vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		logger -t $NAME "failed to save vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+	fi
+
+	log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG"
+	makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG
+	ERROR=$?
+	if [ $ERROR -ne 0 ] ; then
+		log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+		logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+	else
+		scp $KDUMP_TMPDMESG $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE
+		ERROR=$?
+	fi
+
+	panic "test"
+	# did we succeed?
+	if [ $ERROR == 0 ]; then
+		log_success_msg "$NAME: saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		logger -t $NAME "saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		return 0;
+	else
+		log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		logger -t $NAME "failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
+		return 1;
+	fi
+}
+
 
 
 case "$1" in
@@ -390,7 +459,11 @@ case "$1" in
 	exit 0;
 	;;
   savecore)
-	kdump_save_core
+	if ! [ -z $SSH ] || ! [ -z $NFS ] || [ -z NFS4 ]];then
+		kdump_save_core_to_ssh
+	else
+		kdump_save_core
+	fi
 	exit $?
 	;;
   help|-h*|--h*)
